on:
  push:
    branches:
      - default
  workflow_dispatch:
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/checkout@v2
      - run: dotnet build -c Release
      - run: dotnet test -c Release --no-build
      - run: dotnet publish -c Release --no-build -o ./dotnet-publish/
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dotnet-publish/
